name: packaging
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build_source_dist:
    name: Build source distribution
    if: startsWith(github.event.ref, 'refs/tags/v')

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build
        run: python -m pip install build

      - name: Run build
        run: python -m build

      - uses: actions/upload-artifact@v4
        with:
          name: source-artifact  # Same name for both uploads
          path: ./dist/*.tar.gz

      - uses: actions/upload-artifact@v4
        with:
          name: wheel-artifact  # Same name for both uploads
          path: ./dist/*.whl

  publish:
    name: Publish package
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs:
      - build_source_dist

    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: source-artifact
          path: ./dist

      - uses: actions/download-artifact@v4
        with:
          name: wheel-artifact
          path: ./dist

      - uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
